[2014-03-21 14:58:11.110000]
ERROR
	Log observer <bound method FileLogObserver.emit of <twisted.python.log.FileLogObserver instance at 0x03027A08>> failed.
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\twisted\internet\posixbase.py", line 261, in _disconnectSelectable
    selectable.connectionLost(f)
  File "D:\Python27\lib\site-packages\twisted\internet\tcp.py", line 474, in connectionLost
    self.connector.connectionLost(reason)
  File "D:\Python27\lib\site-packages\twisted\internet\base.py", line 1066, in connectionLost
    self.factory.doStop()
  File "D:\Python27\lib\site-packages\twisted\internet\protocol.py", line 68, in doStop
    log.msg("Stopping factory %r" % self)
--- <exception caught here> ---
  File "D:\Python27\lib\site-packages\twisted\python\log.py", line 205, in msg
    self.observers[i](actualEventDict)
  File "D:\Python27\lib\site-packages\twisted\python\log.py", line 402, in emit
    util.untilConcludes(self.flush)  # Hoorj!
  File "D:\Python27\lib\site-packages\twisted\python\util.py", line 776, in untilConcludes
    return f(*a, **kw)
exceptions.IOError: [Errno 22] Invalid argument

